#ifdef QIFTOP_HAVE_BPF

#include "backend/linux/BpfBirthReader.h"

#include <cerrno>
#include <cstdarg>
#include <cstdio>
#include <ctime>
#include <mutex>
#include <unistd.h>

#include <linux/types.h>
#include <bpf/libbpf.h>

#include <QElapsedTimer>

#include "backend/linux/BirthDecode.h"
#include "backend/linux/bpf/birth_events.h"
#include "util/Logging.h"

#include "birth.skel.h" // generated by bpftool (name qiftop_birth) — embeds the .o

namespace qiftop::backend::linuximpl {

namespace {

// Process-wide CLOCK_MONOTONIC ms, the same base BirthCache TTLs against. One
// shared timer so every reader/record agrees on "now".
qint64 monoMsNow()
{
    static const QElapsedTimer t = [] {
        QElapsedTimer e;
        e.start();
        return e;
    }();
    return t.elapsed();
}

// Route libbpf's own logging into our verbose category instead of stderr.
int libbpfPrint(enum libbpf_print_level level, const char *fmt, va_list args)
{
    if (level == LIBBPF_DEBUG)
        return 0;
    char buf[512];
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    qCWarning(lcVerbose).noquote() << "libbpf:" << QString::fromUtf8(buf).trimmed();
    return 0;
}

} // namespace

BpfBirthReader::BpfBirthReader(Sink sink) : m_sink(std::move(sink))
{
    m_clkTck = ::sysconf(_SC_CLK_TCK);
    if (m_clkTck <= 0)
        m_clkTck = 100; // USER_HZ is 100 on Linux; sane fallback
}

BpfBirthReader::~BpfBirthReader()
{
    stop();
}

bool BpfBirthReader::start()
{
    if (m_running.load())
        return true;

    static std::once_flag once;
    std::call_once(once, [] { libbpf_set_print(libbpfPrint); });

    m_skel = qiftop_birth__open();
    if (!m_skel) {
        qCWarning(lcVerbose) << "bpf birth: skeleton open failed "
                                "(no kernel BTF / libbpf?) — conntrack-only";
        return false;
    }
    if (qiftop_birth__load(m_skel) != 0) {
        qCWarning(lcVerbose) << "bpf birth: program load failed "
                                "(kernel BTF / verifier?) — conntrack-only";
        qiftop_birth__destroy(m_skel);
        m_skel = nullptr;
        return false;
    }

    // Per-probe TOLERANT attach: attach each program individually and keep the
    // ones that take. A kernel where one traced function is renamed/inlined/not
    // attachable (or hits the trampoline limit) still yields birth attribution
    // from the probes that DID attach, instead of losing all of it. (Load above
    // is necessarily whole-object — CO-RE relocation/verification is per-object;
    // if THAT fails nothing is attachable anyway.)
    int total = 0;
    bpf_program *prog = nullptr;
    bpf_object__for_each_program(prog, m_skel->obj) {
        ++total;
        bpf_link *link = bpf_program__attach(prog);
        if (!link) {
            qCWarning(lcVerbose).noquote()
                << "bpf birth: probe" << QString::fromUtf8(bpf_program__name(prog))
                << "attach failed — skipped (other probes continue)";
            continue;
        }
        m_links.push_back(link);
    }
    if (m_links.empty()) {
        qCWarning(lcVerbose) << "bpf birth: no probes attached "
                                "(CAP_BPF / CONFIG_FUNCTION_TRACER?) — conntrack-only";
        qiftop_birth__destroy(m_skel);
        m_skel = nullptr;
        return false;
    }

    m_rb = ring_buffer__new(bpf_map__fd(m_skel->maps.births),
                            &BpfBirthReader::onRingEvent, this, nullptr);
    if (!m_rb) {
        qCWarning(lcVerbose) << "bpf birth: ring_buffer__new failed — conntrack-only";
        for (bpf_link *l : m_links)
            bpf_link__destroy(l);
        m_links.clear();
        qiftop_birth__destroy(m_skel);
        m_skel = nullptr;
        return false;
    }

    m_stop.store(false);
    m_running.store(true);
    m_thread = std::thread([this] { drainLoop(); });
    qCInfo(lcVerbose).noquote()
        << QStringLiteral("bpf birth: attached %1/%2 probes; draining ring buffer")
               .arg(m_links.size())
               .arg(total);
    return true;
}

void BpfBirthReader::stop()
{
    m_stop.store(true);
    if (m_thread.joinable())
        m_thread.join();
    if (m_rb) {
        ring_buffer__free(m_rb);
        m_rb = nullptr;
    }
    for (bpf_link *l : m_links)
        bpf_link__destroy(l);
    m_links.clear();
    if (m_skel) {
        qiftop_birth__destroy(m_skel);
        m_skel = nullptr;
    }
    m_running.store(false);
}

int BpfBirthReader::onRingEvent(void *ctx, void *data, unsigned long size)
{
    auto *self = static_cast<BpfBirthReader *>(ctx);
    if (size < sizeof(qiftop_birth_event))
        return 0; // truncated / version skew — skip
    const auto *ev = static_cast<const qiftop_birth_event *>(data);
    const DecodedBirth d = decodeBirth(*ev, self->m_clkTck, monoMsNow());
    if (self->m_sink)
        self->m_sink(d.key, d.rec);
    return 0;
}

void BpfBirthReader::drainLoop()
{
    // Block up to 200 ms per poll so stop() is observed promptly without
    // busy-spinning. ring_buffer__poll wakes immediately when events arrive.
    while (!m_stop.load()) {
        const int n = ring_buffer__poll(m_rb, 200 /*ms*/);
        if (n < 0 && n != -EINTR) {
            qCWarning(lcVerbose) << "bpf birth: ring poll error" << n << "— stopping reader";
            break;
        }
    }
}

} // namespace qiftop::backend::linuximpl

#endif // QIFTOP_HAVE_BPF
